[project]
name = "Reproducible_modelling_Exercise2"
version = "0.1.0"
description = "Add a short description here"
authors = ["DLFStouten <166629646+DLFStouten@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["win-64"]

[tasks]

[dependencies]
cookiecutter = ">=2.6.0,<2.7"
jinja2-time = ">=0.2.0,<0.3"
dvc = ">=3.48.2"
imod = "0.15.3.*"
snakemake = ">=8.14.0,<8.15"
